# Структуры данных

Работая с большим количеством одинаковых данных их удобно хранить в структурированном виде, что позволяет обращатся к ним систематизированно<br>

**Julia** поддерживает следующие структуры данных:
1. Кортежи (Tuples)
2. Словари (Dictionaries)
3. Массивы (Arrays)

<br>
Коротко их можно охарактеризовать следующим образом - массивы и кортежи являются упорядаченными структурами (доступ к элементам можно получить по их номеру), словари и массивы - редактируемые структуры.

## Кортежи

Мы можем создать кортеж путем помещения упорядоченой коллекции элементов в круглые скобки `( )`.

Синтаксис: <br>
```julia
(элемент1, элемент2, ...)
```


In [1]:
myfavoriteanimals = ("Пингвины", "Коты", "Сахарные летяги")

("Пингвины", "Коты", "Сахарные летяги")

Доступ к элемента осуществляется по их индексу,

In [2]:
myfavoriteanimals[1]

"Пингвины"

но поскольку кортежи нередактируемые, мы не можем изменить их элементы

In [3]:
myfavoriteanimals[1] = "Вомбаты"

MethodError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

##  Именнованные кортежи

Начиная с версии 1.6 **Julia** поддерживает именнованные массивы, в которых каждый элемент кроме номера также имеет свое имя. Для добавления имени необходимо использовать `=` внутри кортежа:

```julia
(name1 = item1, name2 = item2, ...)
```

In [4]:
myfavoriteanimals_1 = (bird = "Пингвины", mammal = "Коты", marsupial = "Сахарные летяги")

(bird = "Пингвины", mammal = "Коты", marsupial = "Сахарные летяги")

Как и обычные кортежи, именнованные кортежи позволяют обращатся к элементам по номеру:

In [7]:
myfavoriteanimals_1[1]

"Пингвины"

Но так же к ним можно образатся по имени:

In [8]:
myfavoriteanimals_1.bird

"Пингвины"

## Словари

Для хранения набора парных данных удобно использовать словари. Для создания словаря необходимо использовать функцию `Dict()`.

Синтаксис:
```julia
Dict(ключ1 => значение1, ключ2 => значение2, ...)
```

Хороший пример - записная книжка, где каждому имени соответствует номер телефона.

In [9]:
myphonebook = Dict("Деннис" => "+7(977) 53-09-668", "Охотники за превидениями" => "555-2368")

Dict{String, String} with 2 entries:
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

В данном примере каждые имя и номер являются парой "ключ" и "значение". Мы можем узнать номер Денниса используяю соответствующий ключ

In [10]:
myphonebook["Деннис"]

"+7(977) 53-09-668"

Мы можем добавить новую запись в словарь просто путем присваивания

In [11]:
myphonebook["Жди меня"] = "8-800-700-84-36"

"8-800-700-84-36"

Теперь записная книжка выглядит следующим образом

In [12]:
myphonebook

Dict{String, String} with 3 entries:
  "Жди меня"                 => "8-800-700-84-36"
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

Удаление элементов осуществляется при помощи функции `pop!`

In [13]:
pop!(myphonebook, "Жди меня")

"8-800-700-84-36"

In [14]:
myphonebook

Dict{String, String} with 2 entries:
  "Деннис"                   => "+7(977) 53-09-668"
  "Охотники за превидениями" => "555-2368"

В отличии от кортежей и массивов, словари не упорядоченны, поэтому мы не можем обращатся к их элементам по индексу

In [15]:
myphonebook[1]

KeyError: KeyError: key 1 not found

В примере выше **Julia** считает, что вы пытаетесь обратиться к элементу с ключем `1`.

Для получения списка всех доступных ключей можно использовать функцию ```keys```

In [16]:
keys(new_dict)

UndefVarError: UndefVarError: `new_dict` not defined

## Массивы

Как уже говорилось, в отличии от кортежей, массивы могут быть изменены, а в отличии от словарей - данные в массиве упорядочены.<br>
Самым простым способо определить массив является перечисление его элементов в квадратных скобках `[ ]`.

Синтаксис: <br>
```julia
[элемент1, элемент2, ...]
```

К примеру, мы можем создать массив студентов

In [17]:
students = ["Иванов", "Петров", "Васечкин", "Сидоров", "Солтыков-Щедрин"]

5-element Vector{String}:
 "Иванов"
 "Петров"
 "Васечкин"
 "Сидоров"
 "Солтыков-Щедрин"

После того, как массив создан, мы моем получить доступ к его элемента по их индексу. Индексация в **Julia** начинается с 1.

In [18]:
students[3]

"Васечкин"

Таким же образом, мы можем менять его элементы

In [19]:
students[3] = "Соломоненко"

"Соломоненко"

In [20]:
students

5-element Vector{String}:
 "Иванов"
 "Петров"
 "Соломоненко"
 "Сидоров"
 "Солтыков-Щедрин"

Так же, имеется несколько функции определяющих массив заданной формы:

In [21]:
ones_ = ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [42]:
zeros_ = zeros(4,2)

4×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [23]:
rands_ = rand(2,3,1)

2×3×1 Array{Float64, 3}:
[:, :, 1] =
 0.106653  0.767319  0.343381
 0.387152  0.893063  0.0535204

Эти функции работают схожим образом - они возвращают массив заданного размера, состоящий из единиц, нулей или случайных чисел.<br>
Как можно было заметить, тип у них отличается: в первом случае это `Vector{Float64}`, во втором `Matrix{Float64}` и в третьем - `Array{Float64,3}`. На самом деле `Vector{T}` и `Matrix{T}` - это всего лишь псевдонимы для `Array{T,1}` и `Array{T,2}`, где `T` - это тип компонентов массива.

В **Julia** полезно заранее объявлять массив - это позволяет оптимизировать вычисления. Для этого существует универсальный конструктор массивов 

In [24]:
arr_1 = Array{Int64}(undef, 3,5)

3×5 Matrix{Int64}:
  85899345940  3018925951920  3018954030384  3018948832912  281474976776449
 133143986202  3018948832656  3018954030480  3018948832976                1
 146028888096  3018954030288  3018948832848  3018954030240    3018966907968

Здесь `undef` - ключевое слово, которое означает, что массив элементы массива не иницализируются при ео объявлении. Сразу после объявления в них будет находиться "*мусор*" из памяти.<br>
В объявленный таким образом массив уже не получится занести элемент другой типа:

In [25]:
arr_1[1,1] = 3.5

InexactError: InexactError: Int64(3.5)

В случае, если заранее не известно, какого типа элементы могут храниться в массиве, в качестве типа можно указать `Any`

In [26]:
arr_2 = Array{Any}(undef, 4,4)

4×4 Matrix{Any}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [28]:
fibonacci = Array{Float64}([1, 1, 2, 3, 5, 8, 13])

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

При создании массива с содержимым разного типа, ему будет автоматически присвоен тип `Array{Any}`

In [29]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Vector{Any}:
 1
 1
 2
 3
  "Ted"
  "Robyn"

Для редактирования массивов так же имеются функции `push!` и `pop!`. `push!` добавляет элементы в конец массива, а `pop!` удаляет последний элемент из массива.

In [30]:
push!(fibonacci, 21)

8-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0
 21.0

In [31]:
pop!(fibonacci)

21.0

In [32]:
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

Поскольку массив - это тоже тип данных, мы можем определять массив массивов:

In [33]:
favorites = [["koobideh", "chocolate", "eggs"],["penguins", "cats", "sugargliders"]]

2-element Vector{Vector{String}}:
 ["koobideh", "chocolate", "eggs"]
 ["penguins", "cats", "sugargliders"]

При этом, они не обяаны быть совместимй размерности:

In [37]:
numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]


3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

Однако не следует путать их с двумерными массивами (или матрицами) - доступ к элементам осуществляется по разному

In [38]:
numbers[1][2]

2

In [39]:
numbers[1,2]

BoundsError: BoundsError: attempt to access 3-element Vector{Vector{Int64}} at index [1, 2]

In [40]:
zeros_[2,2]

0.0

In [41]:
zeros_[2][2]

BoundsError: BoundsError: attempt to access Float64 at index [2]

**Будте остороны при копировании массивов!**

In [43]:
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [44]:
somenumbers = fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [45]:
somenumbers[1] = 404

404

In [46]:
fibonacci

7-element Vector{Float64}:
 404.0
   1.0
   2.0
   3.0
   5.0
   8.0
  13.0

Редактирование `somenumbers` привело к изменению переменной `fibonacci`!

В данном примере мы, в де1ствительности, не копировали переменную `fibonacci`. Мы просто создали новую ссылку для доступа к объекту `fibonacci`.

Если нам необходимо создать компию массива `fibonacci`, необходимо использовать функцию `copy`.

In [47]:
# Для начала, восcтановим fibonacci
fibonacci[1] = 1
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [48]:
somemorenumbers = copy(fibonacci)

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

In [49]:
somemorenumbers[1] = 404

404

In [50]:
fibonacci

7-element Vector{Float64}:
  1.0
  1.0
  2.0
  3.0
  5.0
  8.0
 13.0

### Упражнения

#### 3.1 
Создайте массив `a_ray` с элементами `[1, 2, 3]`

In [51]:
a_ray = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

Добавьте `4` в конец массива.

In [52]:
push!(a_ray, 4)

4-element Vector{Int64}:
 1
 2
 3
 4

In [53]:
@assert a_ray == [1, 2, 3, 4]

и удалите ее

In [55]:
pop!(a_ray)

4

In [56]:
@assert a_ray == [1, 2, 3]

#### 3.2 
Добавьте в записную книжку `myphonebook` телефон пожарной `101`?

In [61]:
myphonebook["пожарная"] = "101"

Dict("Деннис" => "+7(977) 53-09-668", "Охотники за превидениями" => "555-2368", "пожарная" => "101")


#### 3.3 
Создайте переменную `flexible_phonebook` , в которой могли бы хранится номера как в строковом, так и в численном виде, и добавьте туда номера *Денниса* и *Охотников за превидениями*.



In [66]:
flexible_phonebook = Dict{String, Any}("Dennis" => "8-800-555-35-35", "Ohotniki_za_PRIVIDENIYAMI" => "89999454556")

Dict{String, Any} with 2 entries:
  "Dennis"                    => "8-800-555-35-35"
  "Ohotniki_za_PRIVIDENIYAMI" => "89999454556"

In [67]:
@assert typeof(flexible_phonebook) == Dict{String, Any}